# Generated by Django 3.2.7 on 2021-09-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210926_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotext',
            name='created',
            field=models.DateTimeField(default='2021-09-26'),
        ),
    ]
